# note: this would require --privileged
# FROM ubuntu:bionic
# ARG DISTRO=bionic

ARG DISTRO=focal
ARG CLANG_MAJOR=12
ARG QT_MAJOR=62
ARG QT_VERSION=6.2.0
ARG QBS_VERSION=1.20.1
ARG RUNTIME_APT
ARG RUNTIME_XENIAL="libicu55 libglib2.0-0"
ARG RUNTIME_FOCAL="libicu66 libglib2.0-0 libpcre2-16-0"

FROM ubuntu:${DISTRO} AS clang-base
ARG DISTRO
ARG CLANG_MAJOR

ENV \
    APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 \
    DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

# install Clang (https://apt.llvm.org/)
RUN apt-get update --quiet \
    && apt-get upgrade --yes --quiet \
    && apt-get install --yes --quiet --no-install-recommends \
    wget \
    gnupg \
    apt-transport-https \
    ca-certificates \
    && wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
    && echo "deb http://apt.llvm.org/${DISTRO}/ llvm-toolchain-${DISTRO}-${CLANG_MAJOR} main" > /etc/apt/sources.list.d/llvm.list \
    && apt-get update --quiet \
    && apt-get install --yes --quiet --no-install-recommends \
    clang-${CLANG_MAJOR} \
    lld-${CLANG_MAJOR} \
    libc++abi-${CLANG_MAJOR}-dev \
    libc++-${CLANG_MAJOR}-dev \
    && update-alternatives --install /usr/bin/cc cc /usr/bin/clang-${CLANG_MAJOR} 100 \
    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-${CLANG_MAJOR} 100 \
    && update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${CLANG_MAJOR} 100 \
    && update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${CLANG_MAJOR} 100 \
    && update-alternatives --install /usr/bin/ld ld /usr/bin/ld.lld-${CLANG_MAJOR} 10 \
    && update-alternatives --install /usr/bin/ld ld /usr/bin/ld.gold 20 \
    && update-alternatives --install /usr/bin/ld ld /usr/bin/ld.bfd 30 \
    && c++ --version \
    && apt-get --yes autoremove \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# compile & install Qbs
FROM clang-base AS qbs-build
ARG DISTRO
ARG QT_MAJOR
ARG QT_VERSION
ARG QBS_VERSION

ENV \
    QTDIR=/opt/qt/${QT_VERSION}/gcc_64/ \
    PATH=/opt/qt/${QT_VERSION}/gcc_64/bin:/opt/qbs/bin:${PATH} \
    LD_LIBRARY_PATH=/opt/qt/${QT_VERSION}/gcc_64/lib:${LD_LIBRARY_PATH} \
    PKG_CONFIG_PATH=/opt/qt/${QT_VERSION}/gcc_64/lib/pkgconfig:${PKG_CONFIG_PATH}

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    git \
    cmake \
    make \
    libgl1-mesa-dev \
    python3 \
    python3-pip \
    build-essential \
    libdbus-1-3 \
    libpulse-mainloop-glib0 \
    && apt-get --yes autoremove \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN pip3 install aqtinstall \
    && aqt install-qt --outputdir /opt/qt/ linux desktop ${QT_VERSION} gcc_64

RUN \
    mkdir -p /opt/qbs \
    && wget -qO - https://download.qt.io/official_releases/qbs/${QBS_VERSION}/qbs-linux-x86_64-${QBS_VERSION}.tar.gz | tar xvz --strip=1 -C /opt/qbs

# compile & install Qbs
FROM qbs-build AS plugin-build
ARG DISTRO
ARG QT_MAJOR
ARG QT_VERSION
ARG QBS_VERSION

# install plugins
RUN git clone --branch 6.2.0 --depth 1 git://code.qt.io/qt/qtbase.git /opt/qtbase \
    && cd /opt/qtbase/src/plugins/sqldrivers \
    && apt-get -y update  \
    && apt-get install -y libmysqlclient-dev \
    libpq-dev \
    build-essential \
    ninja-build \
    && mkdir build \
    && cd build \
    && cmake -GNinja .. \
    && cmake --build . \
    && cmake --install . \
    && cd / \
    && rm -rf /opt/qtbase

# final qbs-clang-qt (with Qt)
FROM plugin-build AS qbs-clang-qt
ARG DISTRO
ARG CLANG_MAJOR
ARG QT_MAJOR
ARG QT_VERSION
ARG QBS_VERSION
ARG RUNTIME_APT
ARG RUNTIME_FOCAL
ARG RUNTIME_XENIAL

LABEL Description="Ubuntu ${DISTRO} - Clang${CLANG_MAJOR} + Qt ${QT_VERSION} + Qbs ${QBS_VERSION}"

COPY --from=qbs-build /opt/qbs /opt/qbs
COPY --from=qbs-build /opt/qt/${QT_VERSION}/gcc_64/ /opt/qt${QT_MAJOR}
ENV \
    QTDIR=/opt/qt${QT_MAJOR} \
    PATH=/opt/qt${QT_MAJOR}/bin:/opt/qbs/bin:${PATH} \
    LD_LIBRARY_PATH=/opt/qt${QT_MAJOR}/lib/x86_64-linux-gnu:/opt/qt${QT_MAJOR}/lib:${LD_LIBRARY_PATH} \
    PKG_CONFIG_PATH=/opt/qt${QT_MAJOR}/lib/pkgconfig:${PKG_CONFIG_PATH}

RUN apt-get update --quiet \
    && if [ "${RUNTIME_APT}" != "" ] ; then export "RUNTIME_APT2=${RUNTIME_APT}" ; \
    elif [ "${DISTRO}" = "xenial" ] ; then export "RUNTIME_APT2=${RUNTIME_XENIAL}" ; \
    else export "RUNTIME_APT2=${RUNTIME_FOCAL}" ; \
    fi \
    && apt-get install --yes --quiet --no-install-recommends \
    ${RUNTIME_APT2} \
    mysql-client libmysqlclient21 libgssapi-krb5-2 \
    postgresql-client-12 \
    && apt-get --yes autoremove \
    && apt-get clean autoclean \
    && rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/* \
    && qbs setup-toolchains --detect \
    && qbs setup-qt /opt/qt${QT_MAJOR}/bin/qmake qt${QT_MAJOR} \
    && qbs config defaultProfile qt${QT_MAJOR} \
    && qbs config --list

WORKDIR /build