name: Build Docker Images

on: push

jobs:
  qbs-qt5:
    name: "Qt + qbs + clang"
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: focal
            clang_major: 10
            qt: 5.15.2
            qt_major: 515
            qbs_version: 1.20.1
            docker_file: Dockerfile_qt5

          - distro: focal
            clang_major: 12
            qt: 6.2.0
            qt_major: 62
            qbs_version: 1.20.1
            docker_file: Dockerfile_qt6

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to github 
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: debug
        run: | 
          printenv

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Qt ${{ matrix.qt }} + Clang${{ matrix.clang_major }} + Qbs ${{ matrix.qbs_version }}
        uses: docker/build-push-action@v2
        with:
          target: qbs-clang-qt
          context: .
          file: ${{ matrix.docker_file }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/fettpet/qbs_qt_sql_plugins_docker:qt${{ matrix.qt }}-qbs${{ matrix.qbs_version }}-clang${{ matrix.clang_major }}
          build-args: |
            DISTRO=${{ matrix.distro }}
            CLANG_MAJOR=${{ matrix.clang_major }}
            QT_MAJOR=${{ matrix.qt_major }}
            QT_VERSION=${{ matrix.qt }}
            QBS_VERSION=${{ matrix.qbs_version }}
 
